---
weight:
  baseBody: 5.0
  frontBody: 5.0
  rearBody: 5.0
  leg: 2.0
  arm: 3.0
joints:
  - name: front_turn_table_joint
    gearbox:
      ratio: 10
      type: worm
    actuator:
      type: stepper # TODO(clairbee): should it be 'position'|'velocity'?
      torque: 0.5 # TODO(clairbee): replace this with torque curves
      torqueDetent: 0.1
      torqueStalling: 0.72
      driver:
        type: em2rs
        stepper_driver_model: DM556RS
        modbus_prefix: /modbus/bus0
        modbus_leaf_id: 2
        modbus_is_remote: true
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 0
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_body_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.48
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 1
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_left_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 2
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_left_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 3
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_left_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 4
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_right_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 5
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_right_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 6
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_right_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 7
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_turn_table_joint
    gearbox:
      ratio: 10
      type: worm
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 0
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_body_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 1
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_left_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 2
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_left_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 3
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_left_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 4
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_right_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 5
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_right_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 6
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_right_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 7
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000

buses:
  - path: /modbus/$DRIVER_NAME
    driver:
      type: modbus_rtu
      serial_is_remote: false
      serial_dev_name: /dev/ttyAMA0
      serial_baud_rate: 115200
      serial_data: 8
      serial_parity: false
      serial_stop: 1
      serial_flow_control: true
      serial_prefix: /serial/rtu0
