---
weight:
  baseBody: 5.0
  frontBody: 5.0
  rearBody: 5.0
  leg: 2.0
  arm: 3.0
joints:
  - name: front_turn_table_joint
    gearbox:
      ratio: 10
      type: worm
    actuator:
      type: stepper # TODO(clairbee): should it be 'position'|'velocity'?
      torque: 0.5 # TODO(clairbee): replace this with torque curves
      torqueDetent: 0.1
      torqueStalling: 0.72
      driver:
        type: em2rs
        stepper_driver_model: DM556RS
        modbus_prefix: /bus/modbus/rtu0
        modbus_leaf_id: 2
        modbus_is_remote: true
        init:
          - service: /stepper/modbus/set_do1
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0x24 # disengage brakes on power on
            # value: 0xA0  # TODO(clairbee): disengage brakes during the command only
          - service: /stepper/modbus/set_brake_delay_release
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0 # as fast as possible
          - service: /stepper/modbus/set_brake_delay_lock
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0 # as fast as possible
          - service: /stepper/modbus/set_brake_locking_velocity_threshold
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 10 # TODO(clairbee): what is it??? no effect observed!
          - service: /stepper/modbus/set_jog_interval
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 50 # at least 20 commands per second
          - service: /stepper/modbus/set_jog_acc_dec
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0 # accelerate and decelerate as fast as possible
          - service: /stepper/modbus/set_peak_current
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 20 # 2.0A max at this joint
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 0
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  encoder_model: AMT212E
      #  encoder_amt21_addr: 0x04
      #  encoder_readings_per_second: 10.0
      #  serial_bus_prefix: /bus/rs485/line0
  - name: front_body_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.48
      driver:
        type: em2rs
        stepper_driver_model: DM556RS
        modbus_prefix: /bus/modbus/rtu0
        modbus_leaf_id: 3
        modbus_is_remote: true
        init:
          - service: /stepper/modbus/set_do1
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0x24 # enable brake output
            # value: 0xA0  # TODO(clairbee): disengage brakes during the command only
          - service: /stepper/modbus/set_brake_delay_release
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0 # as fast as possible
          - service: /stepper/modbus/set_brake_delay_lock
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0 # as fast as possible
          - service: /stepper/modbus/set_brake_locking_velocity_threshold
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 10 # TODO(clairbee): what is it??? no effect observed!
          - service: /stepper/modbus/set_jog_interval
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 50 # at least 20 commands per second
          - service: /stepper/modbus/set_jog_acc_dec
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 0 # accelerate and decelerate as fast as possible
          - service: /stepper/modbus/set_peak_current
            type: modbus/srv/ConfiguredHoldingRegisterWrite
            value: 20 # 2.0A max at this joint
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 1
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  encoder_model: AMT212E
      #  encoder_amt21_addr: 0x50
      #  encoder_readings_per_second: 10.0
      #  serial_bus_prefix: /bus/rs485/line0
  - name: front_left_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 2
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_left_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 3
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_left_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 4
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_right_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 5
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_right_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 6
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_right_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board1
      #  channel: 7
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_turn_table_joint
    gearbox:
      ratio: 10
      type: worm
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 0
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_body_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 1
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_left_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 2
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_left_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 3
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_left_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 4
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_right_arm_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 5
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_right_arm_inner_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 6
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: rear_right_arm_wheel_joint
    gearbox:
      ratio: 10
      type: planetary
    actuator:
      type: stepper
      torque: 0.4
      torqueDetent: 0.1
      torqueStalling: 0.72
    brake:
      torque: 0.5
      engagedByDefault: true
      #driver:
      #  type: switch
      #  path: /switch/board2
      #  channel: 7
    encoder:
      type: absolute
      #driver:
      #  type: amt21
      #  ppr: 1000
  - name: front_left_arm_camera_servo_lower_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute
  - name: front_left_arm_camera_servo_upper_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute
  - name: front_right_arm_camera_servo_lower_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute
  - name: front_right_arm_camera_servo_upper_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute
  - name: rear_left_arm_camera_servo_lower_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute
  - name: rear_left_arm_camera_servo_upper_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute
  - name: rear_right_arm_camera_servo_lower_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute
  - name: rear_right_arm_camera_servo_upper_joint
    actuator:
      type: servo
      torque: 0.1
    encoder:
      type: absolute

buses:
  - path: /bus/modbus/rtu0
    driver:
      type: modbus_rtu
      serial_is_remote: false
      serial_dev_name: /dev/ttyAMA0
      serial_baud_rate: 115200
      serial_data: 8
      serial_parity: false
      serial_stop: 1
      serial_flow_control: true
      serial_prefix: /serial/modbus_rtu0
  - path: /bus/rs485/line0
    driver:
      type: serial_bus
      serial_is_remote: false
      serial_dev_name: /dev/ttyAMA1
      serial_baud_rate: 115200
      serial_data: 8
      serial_parity: false
      serial_stop: 1
      serial_flow_control: false
      serial_prefix: /serial/rs485_line0
