pwm:
  - type: velocity
    name: front_join_male
    prefix: /front_join_male
    actuator_velocity_min: -3.14
    actuator_velocity_max: 3.14
  - type: velocity
    name: front_join_female
    prefix: /front_join_female
    actuator_velocity_min: -3.14
    actuator_velocity_max: 3.14
  - type: position
    name: front_right_camera_horizontal
    prefix: /front_right_camera_horizontal
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: position
    name: front_right_camera_vertical
    prefix: /front_right_camera_vertical
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: position
    name: front_left_camera_horizontal
    prefix: /front_left_camera_horizontal
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: position
    name: front_left_camera_vertical
    prefix: /front_left_camera_vertical
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: velocity
    name: rear_join_male
    prefix: /rear_join_male
    actuator_velocity_min: -3.14
    actuator_velocity_max: 3.14
  - type: velocity
    name: rear_join_female
    prefix: /rear_join_female
    actuator_velocity_min: -3.14
    actuator_velocity_max: 3.14
  - type: position
    name: rear_right_camera_horizontal
    prefix: /rear_right_camera_horizontal
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: position
    name: rear_right_camera_vertical
    prefix: /rear_right_camera_vertical
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: position
    name: rear_left_camera_horizontal
    prefix: /rear_left_camera_horizontal
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: position
    name: rear_left_camera_vertical
    prefix: /rear_left_camera_vertical
    actuator_position_min: -2.6
    actuator_position_max: 2.6
  - type: position
    name: front_attachment
    prefix: /front_attachment
    actuator_position_min: -3.14
    actuator_position_max: 3.14
  - type: position
    name: rear_attachment
    prefix: /rear_attachment
    actuator_position_min: -3.14
    actuator_position_max: 3.14

uart:
  - serial: /rs485/line1
  - serial: /rs485/line2
  - serial: /rs485/line3
  - serial: /rs485/line4
