---
- name: Configure Raspberry PI for OpenVMP
  hosts: openvmp-pi

  tasks:
    # Basic configuration
    - name: Configure the moto
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "echo 'Welcome to OpenVMP. Use Ansible for any mutable changes.'"
        create: true
    - name: Disable console to free the UART port
      replace:
        dest: /boot/firmware/cmdline.txt
        regexp: "console=[A-Za-z]*0,[0-9]* "
        replace: ""
    - name: Disable Bluetooth to free the UART port - part 1
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        line: "dtoverlay=disable-bt"
        create: false
    - name: Disable Bluetooth to free the UART port - part 2
      ansible.builtin.systemd:
        name: hciuart
        state: stopped
    - name: Disable Bluetooth to free the UART port - part 3
      ansible.builtin.systemd:
        name: bluetooth
        state: stopped
    - name: Setup RaspberryPI RS485 CAN HAT - part 1
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        line: "dtparam=spi=on"
        create: false
    - name: Setup RaspberryPI RS485 CAN HAT - part 2
      ansible.builtin.lineinfile:
        path: /boot/firmware/config.txt
        line: "dtoverlay=mcp2515-can0,oscillator=12000000,interrupt=25,spimaxfrequency=2000000"
        create: false
    - name: Disable unattended upgrades to be in control
      ansible.builtin.apt:
        pkg:
          - unattended-upgrades
        state: absent
    - name: Installing and updating system packages
      ansible.builtin.apt:
        pkg:
          - i2c-tools
          - python3-pip
          - gpsd-tools
        update_cache: true
        state: present
    - name: Installing and updating ROS2
      ansible.builtin.apt:
        pkg:
          - ros-humble-desktop-full
          - ros-humble-ros2-control
          - ros-humble-ros2-controllers
          - python3-colcon-common-extensions
          - ros-humble-camera-calibration-parsers
          - v4l2loopback-utils
          - ros-humble-robot-localization
        update_cache: true
        state: present
    - name: Install socat
      ansible.builtin.apt:
        name: socat
        update_cache: false
        state: present

    # Source code repository
    - name: Creating source code repositories on the targets
      shell: git init openvmp
      args:
        creates: openvmp/.git
      changed_when: False
    - name: Creating source code repositories on the targets
      shell: git config --bool --add receive.denyCurrentBranch true
      args:
        chdir: openvmp
      changed_when: False
    - name: Registering the target repository in the local repository
      command: git remote add target-{{ inventory_hostname }} {{ inventory_hostname }}:openvmp
      args:
        # The documentation suggests to run ansible in the current directory only.
        chdir: ../..
        creates: .git/refs/remotes/target-{{ inventory_hostname }}
      ignore_errors: yes
      become: no
      changed_when: False
      delegate_to: localhost
    # TODO(clairbee): consider dropping the below from 'configure.yml'
    - name: Temporary move to another branch
      shell: git checkout -b tmp
      args:
        chdir: openvmp
        creates: .git/refs/heads/tmp
    - name: Pushing source code changes to the targets
      shell: git push target-{{ inventory_hostname }}
      become: no
      changed_when: False
      delegate_to: localhost
    - name: Checking out the main branch
      shell: "git checkout main && git branch -d tmp"
      args:
        chdir: openvmp
        removes: .git/refs/heads/tmp
    - name: Checking out or updating the submodules if necessary
      shell: git submodule update --recursive --init
      args:
        chdir: openvmp
        # TODO(clairbee): creates: List all submodules here
      environment:
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
