---
- name: Setup new Raspberry PI for OpenVMP
  hosts: openvmp-pi

  tasks:
  tasks:
  - name: 
    ansible.builtin.lineinfile:
      path: /root/.bashrc
      line: "echo 'Welcome to OpenVMP. Use Ansible for any mutable changes.'"
      create: true
  - name: Setup RaspberryPI RS485 CAN HAT
    ansible.builtin.lineinfile:
      path: /boot/firmware/config.txt
      line: "dtoverlay=mcp2515-can0,oscillator=12000000,interrupt=25,spimaxfrequency=2000000"
      create: false
