---
- name: Configure all SBCs for OpenVMP
  hosts:
    - sbc-configured
  gather_facts: yes

  tasks:
    # OS configuration
    - name: Configure the moto
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "echo 'Welcome to OpenVMP. Use Ansible for any mutable changes.'"
        create: true
    - name: Limit journald total disk use
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: "SystemMaxUse=100M"
        create: false
    - name: Limit journald single file size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: "SystemMaxFileSize=10M"
        create: false
    - name: Minimize disk usage on syslog
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: "MaxLevelStore=notice"
        create: false
    - name: Disable unattended upgrades to be in control
      ansible.builtin.apt:
        pkg:
          - unattended-upgrades
        state: absent
    - name: Global sysctl configuration
      ansible.builtin.copy:
        dest: /etc/sysctl.d/999-openvmp.conf
        content: |
          net.ipv4.ipfrag_time = 3
          net.core.rmem_max = 4194304
    - name: Disable Avahi daemon to reduce noise
      ansible.builtin.systemd:
        name: avahi-daemon
        state: stopped
        enabled: false
    - name: Installing and updating system packages
      ansible.builtin.apt:
        pkg:
          - git
          - gnupg
          - lsb-release
          - python3-pip
          - socat
          - net-tools
        update_cache: true
        state: present

    # Install ROS2
    - name: Add repository universe
      shell: add-apt-repository universe -y
    - name: Add ROS2 repo key
      ansible.builtin.apt_key:
        url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
        state: present
    - name: Add ROS2 repo
      ansible.builtin.apt_repository:
        repo: deb http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main
        state: present
    - name: Installing and updating ROS2
      ansible.builtin.apt:
      pkg:
        - ros-humble-desktop-full
        - python3-colcon-common-extensions
      update_cache: false
      state: present

    # Robot source code
    - name: Creating source code repositories on the targets
      shell: git init openvmp
      args:
        creates: openvmp/.git
      changed_when: False
    - name: Creating source code repositories on the targets
      shell: git config --bool --add receive.denyCurrentBranch true
      args:
        chdir: openvmp
      changed_when: False
    - name: Registering the target repository in the local repository
      command: git remote add target-{{ inventory_hostname }} {{ inventory_hostname }}:openvmp
      args:
        # The documentation suggests to run ansible in the current directory only.
        chdir: ../..
        creates: .git/refs/remotes/target-{{ inventory_hostname }}
      ignore_errors: yes
      become: no
      changed_when: False
      delegate_to: localhost
    # TODO(clairbee): consider dropping the below from 'configure.yml'
    - name: Temporary move to another branch
      shell: git checkout -b tmp
      args:
        chdir: openvmp
        creates: .git/refs/heads/tmp
    - name: Pushing source code changes to the targets
      shell: git push target-{{ inventory_hostname }}
      become: no
      changed_when: False
      delegate_to: localhost
    - name: Delete the temporary branch
      shell: "git checkout main && git branch -d tmp"
      args:
        chdir: openvmp
        removes: .git/refs/heads/tmp
    - name: Setting the origin for relative submodule paths
      shell: "git remote add origin https://github.com/openvmp/openvmp.git && git fetch"
      args:
        chdir: openvmp
        creates: .git/refs/remotes/origin
    - name: Checking out or updating the submodules if necessary
      shell: git submodule update --recursive --init
      args:
        chdir: openvmp
        # TODO(clairbee): creates: List all submodules here
      environment:
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

    # Robot configuration
    - name: Create the folder to persist configuration
      ansible.builtin.file:
        path: /root/.openvmp
        state: directory
        mode: "0755"
    - name: Helper script to set the environment variables
      ansible.builtin.copy:
        dest: /root/.openvmp/env.sh
        src: ../shared/files/env.sh
        mode: 0755
    - name: Set the environment variables on each login session
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: source /root/.openvmp/env.sh
        create: true

- import_playbook: configure-spinal-pi4b.yaml
- import_playbook: configure-spinal-rock5b.yaml
- import_playbook: configure-cerebral-nuc.yaml
