---
- name: Run OpenVMP services the spinal target SBCs
  hosts:
    - sbc-spinal
  gather_facts: yes

  tasks:
    # Drivers
    - name: Create the systemd service for the 'drivers' subsystem
      template:
        src: ../shared/templates/subsystem.service
        dest: /lib/systemd/system/openvmp-drivers.service
      vars:
        subsystem_name: drivers
        service_description: "OpenVMP subsystem: device drivers"
        service_requires: rsyslog.service
    - name: Launch the 'drivers' subsystem
      systemd:
        name: openvmp-drivers
        state: restarted
        enabled: true

    # Motion control
    - name: Create the systemd service for the 'motion_control' subsystem
      template:
        src: ../shared/templates/subsystem.service
        dest: /lib/systemd/system/openvmp-motion-control.service
      vars:
        subsystem_name: motion_control
        service_description: "OpenVMP subsystem: motion_control"
        service_requires: openvmp-drivers.service
    - name: Launch the 'motion_control' subsystem
      systemd:
        name: openvmp-motion-control
        state: restarted
        enabled: true

    # Reflection
    - name: Create the systemd service for the 'reflection' subsystem
      template:
        src: ../shared/templates/subsystem.service
        dest: /lib/systemd/system/openvmp-reflection.service
      vars:
        subsystem_name: reflection
        service_description: "OpenVMP subsystem: reflection"
        service_requires: openvmp-motion-control.service
    - name: Launch the 'reflection' subsystem
      systemd:
        name: openvmp-reflection
        state: restarted
        enabled: true

    # 'spinal' target
    - name: Create the systemd target for spinal services
      ansible.builtin.copy:
        dest: /lib/systemd/system/openvmp-spinal.target
        content: |
          [Unit]
          Description=Starting this target starts spinal services
          Requires=openvmp-reflection.service
          After=openvmp-reflection.service
