---
- name: Run the minimal set of OpenVMP software on the target
  hosts: openvmp-pi

  tasks:
    # Meta service
    - name: Create the meta service
      ansible.builtin.copy:
        dest: /lib/systemd/system/openvmp.service
        content: |
          [Unit]
          Description=Stopping this service makes all OpenVMP services stop
          After=rsyslog.service
          [Service]
          ExecStart=true

    # # DDS plumbing
    # - name: Create the systemd service for the 'drivers' subsystem
    #   ansible.builtin.copy:
    #     src: ../shared/files/systemd/dds.service
    #     dest: /lib/systemd/system/openvmp-dds.service
    # - name: Launch the dds plumbing
    #   systemd:
    #     name: openvmp-dds
    #     state: restarted
    #     enabled: true

    # Drivers
    - name: Create the systemd service for the 'drivers' subsystem
      template:
        src: ../shared/templates/subsystem.service
        dest: /lib/systemd/system/openvmp-drivers.service
      vars:
        subsystem_name: drivers
        service_description: "OpenVMP subsystem: device drivers"
        service_requires: rsyslog.service
    - name: Launch the 'drivers' subsystem
      systemd:
        name: openvmp-drivers
        state: restarted
        enabled: true

    # Motion control
    - name: Create the systemd service for the 'motion_control' subsystem
      template:
        src: ../shared/templates/subsystem.service
        dest: /lib/systemd/system/openvmp-motion-control.service
      vars:
        subsystem_name: motion_control
        service_description: "OpenVMP subsystem: motion_control"
        service_requires: openvmp-drivers.service
    - name: Launch the 'motion_control' subsystem
      systemd:
        name: openvmp-motion-control
        state: restarted
        enabled: true

    # Reflection
    - name: Create the systemd service for the 'reflection' subsystem
      template:
        src: ../shared/templates/subsystem.service
        dest: /lib/systemd/system/openvmp-reflection.service
      vars:
        subsystem_name: reflection
        service_description: "OpenVMP subsystem: reflection"
        service_requires: openvmp-motion-control.service
    - name: Launch the 'reflection' subsystem
      systemd:
        name: openvmp-reflection
        state: restarted
        enabled: true

    # 'minimal' target
    - name: Create the systemd target
      ansible.builtin.copy:
        dest: /lib/systemd/system/openvmp-minimal.target
        content: |
          [Unit]
          Description=Starting this target starts the minimum set of services
          Requires=openvmp-reflection.service
          After=openvmp-reflection.service
